name: Test job

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: kumar1992/source_project
        path: ./source_project
    
    - uses: actions/checkout@v2
      with:
        repository: kumar1992/destination_project
        path: ./destination_project
    
    - name: Show Working directory
      run: ls
