name: Test job

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repo
    - uses: actions/checkout@v2
      with:
          path: main
    - name: Checkout destination repo
    - uses: actions/checkout@v2
      with:
          repository: kumar1992/destination_project
          path: destination_project
