name: Test job

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run : |
          echo "[LOG] It contains [newrepo], will update to other repo"
          echo "[LOG] Cloning Newrepo"
          git clone https://github.com/kumar1992/source_project.git
          ls
          cd ..
          echo "--------------------"
          ls
          echo "--------------------"
          git clone https://@github.com/kumar1992/Mydockerproject.git Mydockerproject 
          ls
          echo "--------------------"
          cp source_project/resources/*.txt Mydockerproject/.
          cd Mydockerproject
          ls
          echo "--------------------"
          echo "[LOG] Setup global config"
          git config  user.email "${{ secrets.USER_EMAIL }}"
          git config  user.name "${{ secrets.USER_NAME }}"
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/kumar1992/Mydockerproject.git
          echo "--------------------"
          git add -A
          echo added all files
          echo "--------------------"
          git commit -m "Copying files to mydockerproject"
          echo "Commited all files"
          echo "--------------------"
          git push 
          echo "PUSHED"
          echo "--------------------"
          
