name: Test job

on:
  push:
    branches: [ main ]

jobs:
  Check_out_source_repo:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            path: main

        
  Check_out_destination_repo:
     runs-on: ubuntu-latest
     steps:
         - name: Checkout tools repo
         - uses: actions/checkout@v2
           with:
            repository: kumar1992/destination_project
            path: destination_project
         - run: |
                 ls
            
           
   
     
