name: Test job

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checking out source_project repo
    - uses: actions/checkout@v2
      with:
        repository: kumar1992/source_project
        path: ./source_project

    - name: Checking out destination_project repo
    - uses: actions/checkout@v2
      with:
        repository: kumar1992/destination_project
        path: ./destination_project
    
    - name: Create resource directory in destination_project.
      run: mkdir -p destination_project/resources
    
    - name: Copy the source files to destination_project/resources
      run: cp source_project/resources/source*.txt  destination_project/resources/.
           
    - name: Setup global config
      run: cd destination_project/resources && ls
       
          
      
      
      
