name: Test job

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checking out source_project repo
    - uses: actions/checkout@v2
      with:
        repository: kumar1992/source_project
        path: ./source_project

    - name: Checking out destination_project repo
    - uses: actions/checkout@v2
      with:
        repository: kumar1992/destination_project
        path: ./destination_project
    
    - name: Create resource directory in destination_project.
      run: ls
