name: Test job

on:
  push:
    branches: [ main ]
    paths:
      - 'resources/source*'

jobs:
  Copy_source_to_Mydockerproject:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run : |
          echo "[LOG] Cloning source_project"
          git clone https://@github.com/kumar1992/source_project.git
          ls
          cd source_project
          echo "--------------"
          ls
