name: Test job

on:
  push:
    branches: [ main ]

jobs:
  Copy_source_to_Mydockerproject:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            path: main

        - name: Checkout tools repo
        - uses: actions/checkout@v2
          with:
            repository: kumar1992/destination_project
            path: destination_project
        - run: |
              ls
          
