name: Test job

on:
  push:
    branches: [ main ]
    paths:
      - 'resources/source*'

jobs:
  Copy_source_to_Mydockerproject:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
         github_token: ${{ secrets.TOKEN }}
    - run : |
          echo "[LOG] Cloning source_project"
          git clone https://@github.com/kumar1992/source_project.git source_project
          echo "[LOG] Cloning Mydockerproject"
          git clone https://@github.com/kumar1992/Mydockerproject.git Mydockerproject
          cd Mydockerproject
          echo "[LOG] Creating branch for Mydockerproject"        
          git checkout -b UPDATE-CSV
          cd ..
          echo "[LOG] Create a resources directory if not exist"
          mkdir -p Mydockerproject/resources
          echo "[LOG] Copy the source files to mydockerproject/resources files"
          cp  source_project/resources/source*.txt  Mydockerproject/resources/.
          echo "[LOG] Setup global config"
          git config  user.name "${{ secrets.USER_NAME }}"
          git config credential.helper cache
          echo "[LOG] Add files for staging"
          git add -A
          echo "[LOG] Commit the changes>"
          git commit -m "Copying source files to mydockerproject/resources"
          echo "[LOG] Push the changes to branch"
          git push https://${{ secrets.TOKEN }}:@github.com/kumar1992/Mydockerproject
          echo "--------------------"              

