name: Test job

on:
  push:
    branches: [ main ]
    paths:
      - 'resources/source*'

jobs:
  Copy_source_to_Mydockerproject:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run : |
          echo "[LOG] Cloning source_project"
          cd ..
          echo "[LOG] Cloning destination_project"
          git clone https://@github.com/kumar1992/destination_project.git destination_project
          cd destination_project
          echo "[LOG] Creating branch for destination_project"        
          git checkout -b UPDATE-CSV
          cd ..
          ls
          
