name: Test job

on:
  push:
    branches: [ main ]
    paths:
      - 'resources/source*'

jobs:
  Copy_source_to_Mydockerproject:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run : |
          echo "[LOG] Cloning source_project"
          git clone https://@github.com/kumar1992/source_project.git source_project
          echo "[LOG] Cloning Mydockerproject"
          git clone https://@github.com/kumar1992/Mydockerproject.git Mydockerproject
          cd Mydockerproject
          echo "[LOG] Creating branch for Mydockerproject"        
          git checkout -b UPDATE-CSV
          echo "[LOG] Create a resources directory if not exist"
          mkdir -p Mydockerproject/resources
          echo "[LOG] Copy the source files to mydockerproject/resources files"
          ls
          cd source_project
          ls
          cd resources
          ls
